# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mint & Molar Dental Care
email: hello@mintmolar.com
description: > # this means to ignore newlines until "baseurl:"
  Mint & Molar Dental Care is a family dentistry practice in Frederick, MD,
  offering unhurried, personalized care including cleanings & checkups,
  cosmetic whitening, and dentistry for kids and families.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mintmolar.com" # the base hostname & protocol for your site

# Collections
collections:
  services:
    output: false
  team:
    output: false

# Build settings
markdown: kramdown
